// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/divination_record.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4948003097195770275),
    name: 'DivinationRecord',
    lastPropertyId: const obx_int.IdUid(16, 5723866098524317621),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2778869937900005769),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1198118935237430364),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4178383103572880825),
        name: 'question',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6167407322348907752),
        name: 'method',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 830802884923682237),
        name: 'rawHexagramNumbersStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3614171615703364950),
        name: 'primaryHexagramId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2706428486105324095),
        name: 'resultingHexagramId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5891533520243925269),
        name: 'changingLinesStr',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4238298586884981032),
        name: 'interpretation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4174436023989137301),
        name: 'actionTaken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4672531347152269277),
        name: 'actualOutcome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5775469651483899974),
        name: 'isResolved',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8749628383766193539),
        name: 'rawHexagramNumbers',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 930113847811558294),
        name: 'changingLines',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5903624958638999895),
        name: 'aiInterpretation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5723866098524317621),
        name: 'methodDetailJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4948003097195770275),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DivinationRecord: obx_int.EntityDefinition<DivinationRecord>(
      model: _entities[0],
      toOneRelations: (DivinationRecord object) => [],
      toManyRelations: (DivinationRecord object) => {},
      getId: (DivinationRecord object) => object.id,
      setId: (DivinationRecord object, int id) {
        object.id = id;
      },
      objectToFB: (DivinationRecord object, fb.Builder fbb) {
        final questionOffset = fbb.writeString(object.question);
        final methodOffset = fbb.writeString(object.method);
        final rawHexagramNumbersStrOffset = object.rawHexagramNumbersStr == null
            ? null
            : fbb.writeString(object.rawHexagramNumbersStr!);
        final changingLinesStrOffset = object.changingLinesStr == null
            ? null
            : fbb.writeString(object.changingLinesStr!);
        final methodDetailJsonOffset = object.methodDetailJson == null
            ? null
            : fbb.writeString(object.methodDetailJson!);
        final interpretationOffset = object.interpretation == null
            ? null
            : fbb.writeString(object.interpretation!);
        final actionTakenOffset = object.actionTaken == null
            ? null
            : fbb.writeString(object.actionTaken!);
        final actualOutcomeOffset = object.actualOutcome == null
            ? null
            : fbb.writeString(object.actualOutcome!);
        final rawHexagramNumbersOffset = object.rawHexagramNumbers == null
            ? null
            : fbb.writeListInt64(object.rawHexagramNumbers!);
        final changingLinesOffset = fbb.writeListInt64(object.changingLines);
        final aiInterpretationOffset = object.aiInterpretation == null
            ? null
            : fbb.writeString(object.aiInterpretation!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(2, questionOffset);
        fbb.addOffset(3, methodOffset);
        fbb.addOffset(4, rawHexagramNumbersStrOffset);
        fbb.addInt64(5, object.primaryHexagramId);
        fbb.addInt64(6, object.resultingHexagramId);
        fbb.addOffset(7, changingLinesStrOffset);
        fbb.addOffset(8, interpretationOffset);
        fbb.addOffset(9, actionTakenOffset);
        fbb.addOffset(10, actualOutcomeOffset);
        fbb.addBool(11, object.isResolved);
        fbb.addOffset(12, rawHexagramNumbersOffset);
        fbb.addOffset(13, changingLinesOffset);
        fbb.addOffset(14, aiInterpretationOffset);
        fbb.addOffset(15, methodDetailJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final questionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final methodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final rawHexagramNumbersStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final primaryHexagramIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final resultingHexagramIdParam = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 16);
        final changingLinesStrParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final interpretationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final actionTakenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final actualOutcomeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final isResolvedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final object =
            DivinationRecord(
                id: idParam,
                createdAt: createdAtParam,
                question: questionParam,
                method: methodParam,
                rawHexagramNumbersStr: rawHexagramNumbersStrParam,
                primaryHexagramId: primaryHexagramIdParam,
                resultingHexagramId: resultingHexagramIdParam,
                changingLinesStr: changingLinesStrParam,
                interpretation: interpretationParam,
                actionTaken: actionTakenParam,
                actualOutcome: actualOutcomeParam,
                isResolved: isResolvedParam,
              )
              ..rawHexagramNumbers = const fb.ListReader<int>(
                fb.Int64Reader(),
                lazy: false,
              ).vTableGetNullable(buffer, rootOffset, 28)
              ..changingLines = const fb.ListReader<int>(
                fb.Int64Reader(),
                lazy: false,
              ).vTableGet(buffer, rootOffset, 30, [])
              ..aiInterpretation = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 32)
              ..methodDetailJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 34);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DivinationRecord] entity fields to define ObjectBox queries.
class DivinationRecord_ {
  /// See [DivinationRecord.id].
  static final id = obx.QueryIntegerProperty<DivinationRecord>(
    _entities[0].properties[0],
  );

  /// See [DivinationRecord.createdAt].
  static final createdAt = obx.QueryDateProperty<DivinationRecord>(
    _entities[0].properties[1],
  );

  /// See [DivinationRecord.question].
  static final question = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[2],
  );

  /// See [DivinationRecord.method].
  static final method = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[3],
  );

  /// See [DivinationRecord.rawHexagramNumbersStr].
  static final rawHexagramNumbersStr =
      obx.QueryStringProperty<DivinationRecord>(_entities[0].properties[4]);

  /// See [DivinationRecord.primaryHexagramId].
  static final primaryHexagramId = obx.QueryIntegerProperty<DivinationRecord>(
    _entities[0].properties[5],
  );

  /// See [DivinationRecord.resultingHexagramId].
  static final resultingHexagramId = obx.QueryIntegerProperty<DivinationRecord>(
    _entities[0].properties[6],
  );

  /// See [DivinationRecord.changingLinesStr].
  static final changingLinesStr = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[7],
  );

  /// See [DivinationRecord.interpretation].
  static final interpretation = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[8],
  );

  /// See [DivinationRecord.actionTaken].
  static final actionTaken = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[9],
  );

  /// See [DivinationRecord.actualOutcome].
  static final actualOutcome = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[10],
  );

  /// See [DivinationRecord.isResolved].
  static final isResolved = obx.QueryBooleanProperty<DivinationRecord>(
    _entities[0].properties[11],
  );

  /// See [DivinationRecord.rawHexagramNumbers].
  static final rawHexagramNumbers =
      obx.QueryIntegerVectorProperty<DivinationRecord>(
        _entities[0].properties[12],
      );

  /// See [DivinationRecord.changingLines].
  static final changingLines = obx.QueryIntegerVectorProperty<DivinationRecord>(
    _entities[0].properties[13],
  );

  /// See [DivinationRecord.aiInterpretation].
  static final aiInterpretation = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[14],
  );

  /// See [DivinationRecord.methodDetailJson].
  static final methodDetailJson = obx.QueryStringProperty<DivinationRecord>(
    _entities[0].properties[15],
  );
}
